package net.runelite.client.plugins.xTutorialIsland;

import lombok.Getter;
import net.runelite.api.*;
import net.unethicalite.api.items.Equipment;

import javax.inject.Inject;
import java.util.concurrent.ThreadLocalRandom;
import java.util.function.Predicate;


@Getter
public class xTutorialIslandNames {

    public static String[] Usernames = {"Yetea",
            "CHorse",
            "Patrio",
            "Hyenanana",
            "MimicWorm",
            "AmusedVoid",
            "MessySlider",
            "GreedyMinotaur",
            "ClassicDunker",
            "TroubledSpook",
            "Festivalkyrie",
            "GuacaMole",
            "Meerkatnip",
            "Laserpent",
            "DoctorInfant",
            "RhythmFowl",
            "CleverGoliath",
            "FastVillain",
            "MountainMage",
            "CaringJaguar",
            "Ninjafar",
            "Womblast",
            "Spiderby",
            "Boaris",
            "ParallelPalm",
            "EuphoricToffee",
            "PoisonCake",
            "BitterGoddess",
            "RecklessJaguar",
            "GlassChimpanzee",
            "Vipersia",
            "Kimognome",
            "Mantissue",
            "Cobrawl",
            "AwfulChamp",
            "PaperJudge",
            "HopeWarhawk",
            "ArcticMaiden",
            "BrotherFerret",
            "AuntYeti",
            "Mosquitoxic",
            "Locustard",
            "Bombeast",
            "Phoenexus",
            "FalseImmortal",
            "PositiveLocust",
            "FarmSphinx",
            "UnusualZebra",
            "NinjaPhantasm",
            "PrisonOx",
            "Griminal",
            "Consoldier",
            "Parasike",
            "Pelicannon",
            "ForcePepper",
            "SimplePecan",
            "LaughingKiwi",
            "BlackCub",
            "BonyFawn",
            "VoyageAnt",
            "Giantics",
            "Slotherworld",
            "BumblingBee",
            "Ibiscuit",
            "MimicVoid",
            "BrotherThunder",
            "DeliriousFury",
            "SmilingFay",
            "WarSoul",
            "CrashKitty",
            "Panthermal",
            "Pixigh",
            "Demonkey",
            "Preaster",
            "MemoryMinotaur",
            "BruisedDutchess",
            "BathGangster",
            "ExcitedPhantom",
            "PositiveGull",
            "AwfulElephant",
            "Chimpanther",
            "Kappaladin",
            "CLion",
            "Sniperv",
            "GrandTwin",
            "RadioactivePanda",
            "ThunderCow",
            "FarmDeer",
            "ForsakenWitch",
            "WinterMutant",
            "Cheatah",
            "Lavampire",
            "Basshopper",
            "Chimpanzy",
            "BrutishAlien",
            "SillyTerror",
            "RiverSparkle",
            "WittyBlizzard",
            "EveningRock",
            "OriginalOwl" };

}
